// Generated by https://quicktype.io

export interface List {
  itemId:          string;
  itemType:        number;
  itemTitle:       string;
  itemDescription: string;
  photo1:          null;
  photo2:          null;
  photo3:          null;
  itemStartDate:   string;
  itemEndDate:     string;
  itemStartPrice:  number;
  itemStatus:      number;
}
